### ISSUE TITLE
Videos are not appearing for download in the Job Aids section

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw#1331]
Steps to replicate (app was in french):

- Go to Job Aids or "Boite a outils"
- Go to the "Guides" tab
- Nothing appears. What should be appearing are the French videos available to download.

**Comment by rkodev** [comment]
resolved `v0.02`

**Comment by cafootitt** [comment]
Sept 14 and 15 app release versions:

Not fixed; this is still a blank page.

**Comment by cafootitt** [comment]
17 Sept release to preview: lgtm
