### ISSUE TITLE
Vaccine card task should expire at 2 years of age

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw#1334]
Steps to replicate

- Register a 2 year old child
- Open home visit form
- Vaccine card task appears when it shouldn't

Reminder of the schedule:

Task | Trigger Event | Trigger Date | Due date | Overdue | Expiry
-- | -- | -- | -- | -- | --
Child vaccine card | Child Registration | Child's DOB | Child's DOB | Child's DOB + 12 months | DOB + 24 months

**Comment by rkodev** [comment]
resolved `v0.02`

**Comment by cafootitt** [comment]
17 Sept - I am still seeing the vaccine card task

How are we calculating expiry? Is it 2 calendar years? 24 calendar months? or 730 days?

**Comment by rkodev** [comment]
@cafootitt the vaccine card task works by calculating 24 months from DOB. The only issue reproduced was that the day the child turned 2 yrs old was not included in the filter. I've since added this

**Comment by cafootitt** [comment]
22 Sept release - lgtm
