### ISSUE TITLE
Remove extra space between "Deworming" and "1st dose"

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-chw#254]
![Screenshot_20190322-152216](https://user-images.githubusercontent.com/3488986/54826251-73199900-4cc0-11e9-8cac-6f2a8d19b615.png)
![Screenshot_20190322-152427](https://user-images.githubusercontent.com/3488986/54826253-73199900-4cc0-11e9-9c1b-495e187ea03a.png)
![Screenshot_20190322-164614](https://user-images.githubusercontent.com/3488986/54827066-32bb1a80-4cc2-11e9-88b4-d73db81de1b2.png)

**Comment by cagulas** [comment]
I am not seeing this fix in the March 28th release. Can you please check on what happened?

**Comment by ladleo** [comment]
I may have replaced some values to get things working on my local dev and forgot to place them back, fixed now.

**Comment by cagulas** [comment]
@ladleo You missed the last screenshot above on the upcoming services page. Please try to get this wrapped up for the release this week, please.

**Comment by ladleo** [comment]
The issue is addressed already. 
![deworming](https://user-images.githubusercontent.com/10863335/56898265-4dd73200-6a99-11e9-87eb-98e7af8dacd0.jpeg)

**Comment by cagulas** [comment]
No, it's not. I'm referring to the 3rd image in the original comment above. Copying below for ease of reference:

![image](https://user-images.githubusercontent.com/3488986/56899570-68f77100-6a9c-11e9-84ab-5f52b6a31acb.png)

**Comment by ladleo** [comment]
Fixed.
![upcoming_services](https://user-images.githubusercontent.com/10863335/56945734-c5a46b80-6b30-11e9-81d0-84932575ba29.jpeg)

**Comment by cagulas** [comment]
Great, closing this issue then.
